from telegram import Bot
from datetime import datetime
import random
import os

BOT_TOKEN = os.getenv("BOT_TOKEN")
CHAT_ID = os.getenv("CHAT_ID")
THREAD_ID = os.getenv("THREAD_ID")  # kalau pakai topik di grup

motivasi_list = [
    
    "Tiap kali lo refresh harga token, lo bisa aja refresh satu task di Galxe. Pilih yang menghasilkan.",
    "Orang sibuk riset biar ga kena sybil, lo sibuk riset drama influencer. Beda kelas.",
    "Penyakit paling bahaya itu 'ntar aja'. Obatnya cuma satu: 'kerjain sekarang'.",
    "Dompet impianmu nggak akan keisi cuma dengan angan-angan. Isi pake aksi, sekarang.",
    "Snapshot itu buta. Dia cuma ngerekam aksi, bukan niat atau janji-janji manismu.",
    "Alasanmu buat nggak gerak hari ini bakal jadi penyesalan terbesarmu besok.",
    "Lo minta rezeki jutaan, tapi effort lo recehan. Nggak malu sama doa?",
    "Setiap task yang lo skip adalah satu pintu rezeki yang sengaja lo tutup sendiri.",
    "Capek itu perasaan, tapi cuan itu kenyataan. Mau hidup di perasaan atau kenyataan?",
    "Konsistensi itu bukan bakat, tapi keputusan. Ambil keputusanmu hari ini.",
    "Berhenti berharap pada keberuntungan. Bangun keberuntunganmu sendiri lewat setiap klik.",
    "Proyek nggak butuh optimismu, butuhnya transaksimu. Udah berapa tx hari ini?",
    "Waktu nggak akan nunggu lo siap. Waktu cuma jalan terus, ninggalin lo di belakang.",
    "Rasa 'mager' itu cuma sementara, tapi rasa nyesel karena nggak dapet apa-apa itu permanen.",
    "Yang menghalangi lo bukan modal atau skill, tapi tembok 'males' yang lo bangun sendiri.",
    "Badan boleh rebahan, tapi jari harus tetep jalan. Aset digital dibangun dari situ.",
    "Jangan tanya 'kapan listing?'. Tanya 'udah cukup belum farming gue?'",
    "Yang bikin lo miskin bukan keadaan, tapi mental 'ah gampang lah' punya lo itu.",
    "Dev liat log transaksi, bukan liat story Instagram lo. Kontribusi lo mana?",
    "Dompet lo itu cerminan effort lo setahun terakhir. Kalo isinya debu, ya itu hasil lo.",
    "Stop nyalahin 'timing'. Timing terbaik itu kemarin, timing kedua terbaik itu sekarang, bukan besok.",
    "Satu jam lo nge-war di komen, bisa buat 10 wallet baru. Pilih mana: ego atau cuan?",
    "Lo nungguin 'perfect moment'? Orang lain bikin momen itu sendiri dengan farming tiap hari.",
    "Pas snapshot terjadi, yang dihitung itu 'on-chain history', bukan 'on-chat history'.",
    "Lo ngetawain yang gagal dapet airdrop. Padahal dia udah nyoba, lah lo? Nonton doang.",
    "Kalau mental lo masih 'sekali coba langsung berhasil', mending gausah main crypto.",
    "Tiap kali lo refresh harga token, lo bisa aja refresh satu task di Galxe. Pilih yang menghasilkan.",
    "Airdrop itu bukan undian berhadiah, tapi upah buat yang mau kerja.",
    "Lo iri sama hasilnya, tapi jijik sama prosesnya. Gimana mau maju?",
    "Ngeluh 'burnout' padahal baru seminggu. Hunter sejati itu itungannya tahunan, bukan mingguan.",
    "Mending keliatan bodoh karena nanya, daripada keliatan miskin karena gengsi.",
    "Rezeki itu tau alamatnya. Kalo alamat lo cuma di zona nyaman, ya dia ga bakal mampir.",
    "Dompet lo nangis liat orang lain pamer 'eligible'. Salah siapa coba?",
    "Lo nonton tutorial, orang lain udah selesai ngerjain. Beda level.",
    "Ngaku 'smart money' tapi tiap hari cuma retweet-retweet doang. Farmingnya kapan, bos?",
    "Rezeki itu jijik sama yang cuma 'niat doang' tapi nggak gerak.",
    "Kalau niat lo cuma sebatas 'bookmark', rezeki lo juga bakal sebatas angan-angan.",
    "Bukan project-nya yang PHP, tapi ekspektasi lo yang ketinggian buat effort yang seuprit.",
    "Masa depan lo lagi teriak 'TOLONG FARMING SEKARANG!', tapi lo malah asik scroll.",
    "Alasan lo lebih banyak dari jumlah wallet lo. Pantes ga dapet-dapet.",
    "Tiap alesan yang lo buat, ada orang lain yang lagi nyiapin wallet ke-100.",
    "Lo bukan takut rugi gas fee, lo cuma takut capek. Ngaku aja.",
    "Berdoa dapet airdrop tapi task harian dilewatin. Malaikat juga bingung, bro.",
    "Kalau farming cuma nunggu yang gratisan, jangan ngarep hasil jutaan.",
    "Yang miskin itu bukan dompet lo, tapi mental lo yang gampang nyerah.",
    "Setiap klik hari ini adalah satu bata untuk membangun istana finansialmu di masa depan.",
    "Konsistensi kecil setiap hari akan mengalahkan usaha besar yang hanya sesekali. Teruslah bergerak.",
    "Bayangkan hari saat lelahmu terbayar lunas, saat kamu melihat alokasi airdrop dengan senyum. Hari itu akan datang.",
    "Di dalam setiap usahamu, ada potensi untuk mengubah hidup. Percayai prosesmu dan kemampuanmu.",
    "Wajar merasa sistem ini tidak adil. Tapi sistem ini tidak berjalan di atas keadilan, ia berjalan di atas 'bukti kerja'. Perasaanmu tidak terhitung sebagai bukti.",
    "Potensi dirimu itu nyata dan tak terbatas. Tapi tanpa aksi, potensi hanyalah nama lain untuk penyesalan di masa depan.",
    "Merasa terjebak dalam situasi yang sama memang berat. Tapi kadang, 'terjebak' hanyalah cara lain untuk bilang 'terlalu nyaman dengan alasan'.",
    "Lelah karena berjuang itu wajar dan terhormat. Tapi ada juga lelah karena terlalu banyak mengeluh dan tidak melakukan apa-apa.",
    "Kamu berhak untuk istirahat. Tapi dunia dan snapshot tidak akan ikut istirahat menunggumu.",
    "Berharap dapat rezeki besar itu hak semua orang. Tapi rezeki punya standar, dia tidak akan mendatangi harapan yang kosong tanpa usaha.",
    "Tidak ada yang salah dengan menunggu momen yang tepat. Kesalahannya adalah saat sadar bahwa momen itu tidak pernah datang, melainkan diciptakan.",
    "Keraguanmu itu valid, semua orang merasakannya. Tapi keraguan tidak membayar tagihan.",
    "Mengetahui banyak 'alpha' itu hebat. Tapi pengetahuan tanpa eksekusi hanyalah hiburan intelektual, bukan aset.",
    "Wajar jika takut mengambil risiko. Tapi zona amanmu saat ini bisa jadi risiko terbesarmu di masa depan.",
    "Semua orang setuju kamu punya talenta. Tapi dunia tidak memberi penghargaan untuk talenta, dunia memberi penghargaan untuk hasil.",
    "Bermimpi besar itu gratis dan indah. Namun, hidup di dunia nyata butuh lebih dari sekadar mimpi untuk bisa makan.",
    "Kamu boleh menyalahkan keadaan atas posisimu saat ini. Tapi hanya kamu yang punya kuasa untuk mengubahnya.",
    "Menganalisis sampai detail itu tanda kecerdasan. Tapi terlalu banyak analisis tanpa aksi adalah tanda kelumpuhan.",
    "Punya rencana cadangan itu bijak. Tapi terlalu fokus pada rencana cadangan adalah cara halus untuk mempersiapkan kegagalan.",
    "Lelah itu wajar, itu tandanya kamu berjuang. Istirahat sejenak, lalu lanjutkan perjalananmu. Hadiahnya menanti.",
    "Setiap task yang kamu selesaikan adalah investasi waktu untuk dirimu di masa depan. Kamu sedang menanam benih kesuksesan.",
    "Jangan remehkan satu aksi kecil. Dari satu transaksi bisa lahir sebuah kebebasan finansial.",
    "Perjalanan ini adalah maraton, bukan sprint. Nikmati proses belajarnya, rayakan setiap kemajuannya.",
    "Kamu lebih kuat dan lebih mampu dari yang kamu kira. Buktikan itu pada dirimu sendiri hari ini.",
    "Setiap hari adalah kesempatan baru untuk menjadi lebih dekat dengan tujuanmu. Manfaatkan hari ini sebaik-baiknya.",
    "Ingat alasanmu memulai. Jadikan itu bahan bakar saat semangatmu mulai redup.",
    "Ngerasa capek dan pengen udahan itu bagian dari perjalanan ini. Perasaan itu valid.",
    "Wajar kalau kadang bertanya-tanya 'apakah ini semua akan sepadan?'. Keraguan itu manusiawi.",
    "Tidak apa-apa jika hari ini kamu merasa tidak punya energi. Kamu sudah berjuang keras sampai titik ini.",
    "Perjalanan ini memang menguji kesabaran. Ada hari baik, dan ada hari yang terasa sangat berat.",
    "Setiap usaha yang pernah kamu keluarkan, sekecil apapun, punya ceritanya sendiri. Semua itu terekam.",
    "Melewati hari demi hari dalam ketidakpastian itu tidak mudah. Kamu kuat sudah sejauh ini.",
    "Kadang, merasa 'sendirian' dalam perjuangan ini adalah hal yang nyata. Kamu tidak sendirian merasakannya.",
    "Ada kalanya pikiran butuh jeda dari semua ekspektasi. Menarik napas sejenak itu perlu.",
    "Tidak semua hari harus produktif. Ada hari untuk bertahan, dan itu sudah lebih dari cukup.",
    "Melihat orang lain berhasil kadang bisa terasa berat di hati. Itu reaksi yang sangat normal.",
    "Frustrasi karena hasil belum terlihat adalah bagian dari proses. Semua orang yang berjuang merasakannya.",
    "Mengakui bahwa kamu lelah bukanlah tanda kelemahan, itu adalah tanda kesadaran diri.",
    "Ada nilai dalam setiap proses yang dijalani, terlepas dari apapun hasilnya nanti.",
    "Beban terasa berat karena memang yang kamu pikul itu harapan. Wajar jika pundakmu lelah.",
    "Tidak masalah jika yang kamu lakukan hari ini hanyalah bertahan. Bertahan juga sebuah kemenangan.",
    "Kesabaran adalah kunci. Setiap usaha yang kamu tanam akan berbuah pada waktunya, mungkin saat kamu paling tidak menduganya.",
    "Fokus pada kemajuan, bukan kesempurnaan. Satu langkah kecil ke depan jauh lebih baik daripada diam di tempat.",
    "Kamu sedang membangun sesuatu yang besar, bahkan jika saat ini terlihat kecil. Teruslah percaya.",
    "Terima kasih untuk usahamu hari ini. Dirimu di masa depan akan sangat berterima kasih padamu.",
    "Ngiri itu bahan bakar. Kalau lo cuma panas doang tapi mesin nggak nyala, ya percuma.",
    "Capek itu pasti, miskin karena males itu pilihan.",
    "Stop nanya 'masih worth it ga?'. Tanya ke diri sendiri, 'gue pantes ga dapet cuan?'",
    "Nanti pas orang pamer mobil baru dari airdrop, lo masih sibuk nyari airdrop instan di Telegram.",
    "Snapshot itu kayak ujian dadakan. Yang nyontek (baru mulai pas viral) nilainya pasti kecil.",
    "Lo terlalu sibuk cari 'alpha', padahal alpha terbaik adalah 'disiplin'.",
    "Project butuh partisipasi, bukan penonton. Lo mau dibayar buat nonton doang?",
    "Jangan jadi fosil di dunia crypto. Gerak atau punah.",
    "Lo sibuk nyari 'the next big thing', padahal 'the big thing' itu ada di task harian yang lo skip.",
    "Ngeluh soal gas fee tapi tiap hari beli kopi 50 ribu. Prioritas lo aneh.",
    "Dapet 10 dolar dari airdrop ngeluhnya seminggu. Giliran orang dapet 10 ribu dolar, lo cuma bisa bilang 'hoki'.",
    "Mental gratisan itu penyakit. Gak ada yang jadi kaya dari nungguin sedekah.",
    "Stop jadi 'watcher'. Jadilah 'doer'. Dompet lo butuh aksi, bukan tontonan.",
    "Tiap detik lo ragu, ada wallet lain yang posisinya makin di atas lo.",
    "Kalau niat lo cuma sebatas 'bookmark', rezeki lo juga bakal sebatas angan-angan.",
    "Project nggak peduli lo siapa. Mereka cuma peduli wallet lo aktif atau nggak.",
    "Nyesel itu datangnya pas liat temen lo checkout mobil baru, sementara lo masih nanya 'gimana cara mulai?'",
    "Lo itu bukan 'early', lo itu cuma 'late' yang kebanyakan mikir.",
    "Cuan itu jijik sama orang yang kerjanya cuma 'katanya' dan 'nanti'.",
    "Setiap lo bilang 'mager', ada ratusan orang di luar sana yang lagi ngamanin posisi lo.",
    "Lo pikir dev-nya bakal nge-DM lo buat ngingetin snapshot? Bangun, bro.",
    "Lebih baik dompet kosong karena usaha, daripada dompet kosong karena kebanyakan alasan.",
    "Lo bukan 'istirahat', lo itu 'nyerah'. Jujur aja sama diri sendiri.",
    "Tiap detik kemalasanmu hari ini adalah paku yang lo tancepin di peti mati finansialmu.",
    "Itu bukan 'capek', itu 'takut gagal' yang nyamar jadi males. Lawan.",
    "Snapshot itu nggak punya tombol 'undo'. Kelalaian lo hari ini sifatnya final dan permanen.",
    "Harga dirimu sebanding dengan usahamu. Kalo usahamu nol, ya silahkan nilai sendiri.",
    "Berhenti jadi beban buat masa depanmu sendiri. Gerak.",
    "Dompetmu nggak akan terisi dengan 'semoga'. Dia butuh bukti kerja, bukan harapan kosong.",
    "Setiap alasan yang lo ucapkan cuma pupuk buat pohon kemiskinan lo sendiri.",
    "Fokusmu itu energi. Kalo lo pake buat ngeluh, ya hidup lo bakal penuh keluhan, bukan cuan.",
    "Mentalmu itu aset terbesarmu. Kalau lembek, jangan harap bisa ngangkat rezeki yang berat.",
    "Lo nggak butuh motivasi, lo butuh disiplin. Motivasi itu buat anak manja.",
    "Cuan itu nggak akan dateng ngetok pintu rumah orang males. Nggak akan pernah.",
    "Berhenti menyalahkan keadaan. Satu-satunya yang salah di sini adalah standarmu yang terlalu rendah untuk dirimu sendiri.",
    "Badan lo di kasur, tapi otak lo harusnya lagi farming. Sinkronkan itu.",
    "Setiap hari lo punya pilihan: bangun mimpimu, atau tidur lagi dan nonton mimpi orang lain."
]

def kirim_motivasi():
    bot = Bot(token=BOT_TOKEN)
    motivasi = random.choice(motivasi_list)
    tanggal = datetime.now().strftime("%Y-%m-%d")
    message = f"{motivasi}"
    
    if THREAD_ID:
        bot.send_message(chat_id=CHAT_ID, message_thread_id=int(THREAD_ID), text=message)
    else:
        bot.send_message(chat_id=CHAT_ID, text=message)

if __name__ == "__main__":
    kirim_motivasi()
