name: Kirim Motivasi Harian

on:
  schedule:
- cron: "*/5 * * * *" # jam 08:30 WIB
  workflow_dispatch:  # bisa dijalankan manual juga

jobs:
  kirimMotivasi:
    runs-on: ubuntu-latest
    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      CHAT_ID: ${{ secrets.CHAT_ID }}
      THREAD_ID: ${{ secrets.THREAD_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install python-telegram-bot

      - name: Jalankan script motivasi
        run: python main.py